### ISSUE TITLE
website freezing

### ISSUE THREAD

**Issue by sentothecopycat** [jmatg1/florr-io-spawn-alert#1]
every time i open my skills or an ultra spawns the website just freezes

**Comment by jmatg1** [comment]
Update script. If that doesn't work, please tell me what browser you are using.

**Comment by sentothecopycat** [comment]
> Update script. If that doesn't work, please tell me what browser you are using.

thanks it worked just fine

**Comment by sentothecopycat** [comment]
it was solved :)
