### ISSUE TITLE
Florr.io spawn alert script not working properly

### ISSUE THREAD

**Issue by Absence817** [jmatg1/florr-io-spawn-alert#2]
Menu stuck in bottom right I can only click settings and view the servers but it doesnt actually show me the spawns

![Screenshot 2024-03-12 042804](https://github.com/jmatg1/florr-io-spawn-alert/assets/163118293/0dd7d69a-4aa7-4a90-8f71-fd587f8e94a6)

**Comment by jmatg1** [comment]
you got banned
